services:
  stellar-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: stellar-core-dev:ubuntu24.04
    container_name: stellar-core-dev
    hostname: stellar-core
    stdin_open: true
    tty: true
    volumes:
      - ./stellar-core:/root/stellar-core
      - ./workspace:/root/workspace
    ports:
      - "11625:11625"
      - "11626:11626"
    environment:
      - CC=clang-17
      - CXX=clang++-17
      - CXXFLAGS=-stdlib=libc++ -std=c++17
      - LDFLAGS=-stdlib=libc++
    command: /bin/bash
